### ISSUE TITLE
Invalid function names in API schema

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui-templates#2]
![screen shot 2016-01-05 at 10 24 16](https://cloud.githubusercontent.com/assets/497675/12111565/984d5c6e-b396-11e5-9572-04b5770e5fa9.png)

**Comment by ondrejhlavacek** [comment]
Zajímavý teda je, že u nás v UI to šlape, ale v json editoru to na mě vyblilo toto...

Naše UI: 

![screen shot 2016-01-05 at 10 41 16](https://cloud.githubusercontent.com/assets/497675/12111853/e4d50f4e-b398-11e5-934f-8332179e268b.png)

**Comment by Halama** [comment]
Editor nedává pokud je referencované schéma ve kterém jsou další includes.
Upravím to tak že ty referencované schémata budou zase referencovat další schemata bez definitions.
