### ISSUE TITLE
zendesk templates

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/kbc-ui-templates#8]
kachno, pls vymysli dva tři smysluplný templaty pro zendesk

struktura je připravená:

![screen shot 2016-01-28 at 12 05 00](https://cloud.githubusercontent.com/assets/497675/12642638/64a64da2-c5b7-11e5-8aea-d739ef20d51c.png)

jediná změna je v tom, že templates teď budou POUZE pro sekci `jobs`. do `meta` fajlů do description může přijít markdown (hoď tam klidně nějakej dummy)

bude to fungovat tak, že tam bude dropdown, kterým si vybereš jednu z templates a pak tam bude tlačítko, kterým to odpojíš a zobrazíš si teď čistej JSON, v budoucnu editor schématu.

**Comment by kachnitel** [comment]
Moc me nenapada vic nez ty dva, co uz jsem tam daval:

### Tickets a vse k nim
```
  "jobs": [
    {
      "endpoint": "exports/tickets.json",
      "dataType": "tickets_export",
      "params": {
        "start_time": {
          "time": "previousStart"
        },
        "end_time": ""
      },
      "children": [
        {
          "endpoint": "tickets/{id}/audits.json",
          "dataType": "tickets_audits",
          "params": {}
        },
        {
          "endpoint": "tickets/{id}/comments.json",
          "dataType": "tickets_comments",
          "params": {}
        }
      ]
    }
  ]
```

### Basic tickets export + users
```
  "jobs": [
    {
      "endpoint": "exports/tickets.json",
      "dataType": "tickets_export",
      "params": {
        "start_time": {
          "time": "previousStart"
        },
        "end_time": ""
      }
    },
    {
      "endpoint": "users.json",
      "dataType": "users",
      "params": {}
    }
  ]
```

**Comment by ondrejhlavacek** [comment]
Na demo/vývoj to stačí, nechtěl bys pak z toho udělat něco "produkčního" :-)

**Comment by ondrejhlavacek** [comment]
Nejde něco vykopírovat z nějakýho existujícího projektu?

**Comment by kachnitel** [comment]
Prosel jsem projekty ktere nejvic pouzivaji Zendesk, a mozna by se jeste uzilo tohle:

### Tags
```
  "jobs": [
    {
      "endpoint": "tags.json",
      "dataType": "tags"
    }
  ]
```

Podle vseho ten prvni template ani nema moc smysl, nevypada, ze by ho nekdo pouzival. Tickets, users, a prilezitostne tags je co se pouziva.

**Comment by odinuv** [comment]
solved in 175601cc6398a8ee91709aea12f3c4f13e329ce8
